-- Tourist Places Table
CREATE TABLE IF NOT EXISTS tourist_places (
    place_id TEXT PRIMARY KEY,
    place_name TEXT NOT NULL,
    district TEXT NOT NULL,
    category TEXT NOT NULL,
    description TEXT,
    latitude REAL,
    longitude REAL,
    address TEXT,
    entry_fee_inr REAL,
    opening_time TEXT,
    closing_time TEXT,
    best_season TEXT,
    visit_duration_hours REAL,
    popularity_level TEXT,
    family_friendly TEXT,
    adventure_level TEXT,
    accessibility TEXT,
    parking_available TEXT,
    washroom_available TEXT,
    wheelchair_accessible TEXT,
    official_website TEXT,
    image_url TEXT,
    status TEXT,
    created_date TEXT,
    updated_date TEXT
);

-- Visitor Statistics Table
CREATE TABLE IF NOT EXISTS visitor_statistics (
    record_id TEXT PRIMARY KEY,
    place_id TEXT,
    year INTEGER,
    month_number INTEGER,
    month_name TEXT,
    season TEXT,
    domestic_visitors INTEGER,
    foreign_visitors INTEGER,
    total_visitors INTEGER,
    male_visitors INTEGER,
    female_visitors INTEGER,
    children_visitors INTEGER,
    senior_citizen_visitors INTEGER,
    student_visitors INTEGER,
    group_visitors INTEGER,
    solo_visitors INTEGER,
    average_visit_duration_hours REAL,
    average_spending_inr REAL,
    weather_condition TEXT,
    special_event TEXT,
    festival_season TEXT,
    visitor_satisfaction REAL,
    revenue_inr REAL,
    growth_percentage REAL,
    remarks TEXT,
    created_date TEXT,
    updated_date TEXT,
    FOREIGN KEY (place_id) REFERENCES tourist_places(place_id)
);

-- Reviews Table
CREATE TABLE IF NOT EXISTS reviews (
    review_id TEXT PRIMARY KEY,
    place_id TEXT,
    reviewer_name TEXT,
    reviewer_type TEXT,
    age_group TEXT,
    gender TEXT,
    nationality TEXT,
    visit_date TEXT,
    travel_month TEXT,
    travel_season TEXT,
    travel_mode TEXT,
    travel_group TEXT,
    visit_purpose TEXT,
    overall_rating REAL,
    cleanliness_rating REAL,
    accessibility_rating REAL,
    safety_rating REAL,
    facilities_rating REAL,
    value_for_money_rating REAL,
    recommendation_score INTEGER,
    review_title TEXT,
    review_text TEXT,
    review_length INTEGER,
    sentiment TEXT,
    likes INTEGER,
    helpful_votes INTEGER,
    verified_visitor TEXT,
    review_status TEXT,
    created_date TEXT,
    updated_date TEXT,
    FOREIGN KEY (place_id) REFERENCES tourist_places(place_id)
);

-- Hotels Table
CREATE TABLE IF NOT EXISTS hotels (
    hotel_id TEXT PRIMARY KEY,
    place_id TEXT,
    hotel_name TEXT NOT NULL,
    hotel_type TEXT,
    star_rating INTEGER,
    average_rating REAL,
    total_reviews INTEGER,
    price_per_night_inr REAL,
    distance_from_place_km REAL,
    district TEXT,
    address TEXT,
    latitude REAL,
    longitude REAL,
    check_in_time TEXT,
    check_out_time TEXT,
    total_rooms INTEGER,
    available_rooms INTEGER,
    room_type TEXT,
    air_conditioning TEXT,
    free_wifi TEXT,
    parking TEXT,
    restaurant TEXT,
    room_service TEXT,
    swimming_pool TEXT,
    gym TEXT,
    spa TEXT,
    pet_friendly TEXT,
    family_friendly TEXT,
    wheelchair_accessible TEXT,
    airport_shuttle TEXT,
    breakfast_included TEXT,
    cancellation_policy TEXT,
    phone_number TEXT,
    email TEXT,
    official_website TEXT,
    image_url TEXT,
    status TEXT,
    created_date TEXT,
    updated_date TEXT,
    FOREIGN KEY (place_id) REFERENCES tourist_places(place_id)
);

-- Restaurants Table
CREATE TABLE IF NOT EXISTS restaurants (
    restaurant_id TEXT PRIMARY KEY,
    place_id TEXT,
    restaurant_name TEXT NOT NULL,
    restaurant_type TEXT,
    cuisine TEXT,
    average_rating REAL,
    total_reviews INTEGER,
    average_cost_for_two_inr REAL,
    distance_from_place_km REAL,
    district TEXT,
    address TEXT,
    latitude REAL,
    longitude REAL,
    opening_time TEXT,
    closing_time TEXT,
    seating_capacity INTEGER,
    indoor_seating TEXT,
    outdoor_seating TEXT,
    takeaway TEXT,
    home_delivery TEXT,
    online_booking TEXT,
    vegetarian TEXT,
    vegan TEXT,
    non_vegetarian TEXT,
    local_manipuri_food TEXT,
    parking TEXT,
    wheelchair_accessible TEXT,
    family_friendly TEXT,
    payment_method TEXT,
    phone_number TEXT,
    email TEXT,
    official_website TEXT,
    image_url TEXT,
    status TEXT,
    created_date TEXT,
    updated_date TEXT,
    FOREIGN KEY (place_id) REFERENCES tourist_places(place_id)
);

-- Events Table
CREATE TABLE IF NOT EXISTS events (
    event_id TEXT PRIMARY KEY,
    place_id TEXT,
    event_name TEXT NOT NULL,
    event_category TEXT,
    district TEXT,
    venue TEXT,
    description TEXT,
    organizer TEXT,
    contact_person TEXT,
    phone_number TEXT,
    email TEXT,
    official_website TEXT,
    latitude REAL,
    longitude REAL,
    start_date TEXT,
    end_date TEXT,
    start_time TEXT,
    end_time TEXT,
    duration_days INTEGER,
    season TEXT,
    expected_visitors INTEGER,
    registration_required TEXT,
    entry_fee_inr REAL,
    maximum_capacity INTEGER,
    remaining_capacity INTEGER,
    age_restriction TEXT,
    suitable_for TEXT,
    food_available TEXT,
    parking_available TEXT,
    wheelchair_accessible TEXT,
    emergency_medical_service TEXT,
    security_available TEXT,
    event_status TEXT,
    image_url TEXT,
    created_date TEXT,
    updated_date TEXT,
    FOREIGN KEY (place_id) REFERENCES tourist_places(place_id)
);

-- Weather Table
CREATE TABLE IF NOT EXISTS weather (
    weather_id TEXT PRIMARY KEY,
    place_id TEXT,
    year INTEGER,
    month_number INTEGER,
    month_name TEXT,
    season TEXT,
    average_temperature_c REAL,
    minimum_temperature_c REAL,
    maximum_temperature_c REAL,
    humidity_percentage INTEGER,
    rainfall_mm REAL,
    wind_speed_kmph REAL,
    weather_condition TEXT,
    air_quality_index INTEGER,
    uv_index INTEGER,
    visibility_km REAL,
    sunrise_time TEXT,
    sunset_time TEXT,
    tourism_suitability TEXT,
    weather_warning TEXT,
    created_date TEXT,
    updated_date TEXT,
    FOREIGN KEY (place_id) REFERENCES tourist_places(place_id)
);

-- Create indexes for better performance
CREATE INDEX IF NOT EXISTS idx_visitor_place_year ON visitor_statistics(place_id, year);
CREATE INDEX IF NOT EXISTS idx_reviews_place ON reviews(place_id);
CREATE INDEX IF NOT EXISTS idx_hotels_place ON hotels(place_id);
CREATE INDEX IF NOT EXISTS idx_restaurants_place ON restaurants(place_id);
CREATE INDEX IF NOT EXISTS idx_events_place ON events(place_id);
CREATE INDEX IF NOT EXISTS idx_weather_place ON weather(place_id, year, month_number);